### PR TITLE
Add ui for profile screen

### PR DESCRIPTION
**Pull request by lukstbit**
This PR implements the profile UI as seen in the Figma design(issue #10 ). I've added the implementation in the profile feature module but I think it should be put inside the home feature module as it is a main component in the bottom navigation present in the home module.

### How has it been tested?

Locally as this UI isn't yet connected to the rest of the application.

### CODE REVIEW

**Comment by AlexandraDamaschin** [comment]
@lukstbit what do you think about having only the navigation inside the home module and all the other features separated? 
Or maybe having the navigation inside the app module and all the other features being separated?

**Comment by lukstbit** [comment]
@AlexandraDamaschin Sorry for the late response.

> what do you think about having only the navigation inside the home module and all the other features separated?

I think we would be complicating the application too much with too many modules for a small benefit(if any?).

> Or maybe having the navigation inside the app module and all the other features being separated?

I'm not sure how this would work currently, because by using dynamic modules we inverted the module dependency(feature -> app -> other modules) and the app module doesn't have access to the features modules to implement navigation.

**Comment by AlexandraDamaschin** [comment]
@lukstbit sorry for the delay, vacationing period. 
I've worked on a PR and remove for now the dynamic modules as they weren't going to work. Here you can see the changes https://github.com/code4romania/teacher-workout-android/pull/27, but it was also merged into develop. 

Will do a code review for this PR next week if nobody else jumps in before me :)

**Review by AlexandraDamaschin — APPROVED** [review]
Does this improve software quality? Yes

**Pull request merged**
