### PR TITLE
Migrate to kts

### PR DESCRIPTION
**Pull request by AlexandraDamaschin**
### What does it fix?
Migrate gradle files to kts

Closes #XXX

### CODE REVIEW

**Review by alexandru-calinoiu — APPROVED** [review]

**Comment by lukstbit** [comment]
Why not also switch the main `build.gradle` file to .kts?

**Comment by AlexandraDamaschin** [comment]
> Why not also switch the main `build.gradle` file to .kts?
There are all migrated now, not sure what are you referring to?

**Comment by alexandru-calinoiu** [comment]
> Why not also switch the main `build.gradle` file to .kts? @lukstbit

Is there a build file that it did not get switched? I can't find any in this pr

**Comment by lukstbit** [comment]
@AlexandraDamaschin @alexandru-calinoiu My mistake, they are all migrated.

**Pull request merged**
